export const cheatsheets = [
  {
    topic: "git",
    table: "Basic Snapshotting",
    action: "Check file changes",
    visual: "https://images.cheatsheet.cam/images/image-1725759280918.webp",
    gui: "https://images.cheatsheet.cam/images/Screenshot-2024-09-07-at-3.01.22-AM.webp",
    cli: "git ..",
    emoji: "❄️",
    priority: 1,
  },
  {
    topic: "git",
    table: "Basic Snapshotting",
    action: "staging files",
    visual: "https://images.cheatsheet.cam/images/image-1725759280918.webp",
    gui: "https://images.cheatsheet.cam/images/Screenshot%202024-09-07%20at%203.08.50%20AM.webp",
    cli: "git add .",
    emoji: "🔥",
    priority: 2,
  },
  {
    topic: "git",
    table: "Basic Snapshotting",
    action: "check staging area",
    visual: "https://images.cheatsheet.cam/images/image-1725759280918.webp",
    gui: "https://images.cheatsheet.cam/images/Screenshot%202024-09-07%20at%203.23.49%20AM.webp",
    cli: "git status",
    emoji: "❄️",
    priority: 3,
  },
];
